name: doc

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  doc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Build
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - run: python doc.py

      - name: Commit
        uses: EndBug/add-and-commit@v9
        with:
          message: "docs: update README"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
